create table if not exists publishers(
    id			bigint primary key generated by default as identity,
    name		varchar(50) not null
);

create table if not exists books(
    id			bigint primary key generated by default as identity,
    title		varchar(50) not null
);

create table if not exists authors(
    id			bigint primary key generated by default as identity,
    fullname	varchar(50) not null
);