-- CREATE THE MAIN TABLES

create table if not exists publishers(
    id			bigint primary key generated by default as identity,
    name		varchar(50) not null
);

create table if not exists books(
    id			bigint primary key generated by default as identity,
    title		varchar(50) not null
);

create table if not exists authors(
    id			bigint primary key generated by default as identity,
    fullname	varchar(50) not null
);

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

-- SET THE FIRST RELATIONSHIP
-- ADD FK IN BOOKS TO REFERENCE A PUBLISHER ID

-- NOTE: Ideally, it would be a NOT NULL column. For that the process is:
--      1. Create column allowing null
--      2. Fill values with a valid publisher id
--      3. Alter column to be not null
--      4. Add the FK constraint


alter table if exists books
    add column publisher_id bigint;

-- Use the following command if you already have books created and need to set a publisher_id for it
-- update books
--     set publisher_id = 2;

alter table if exists books
    alter publisher_id set NOT null;

alter table if exists books(
    add constraint book_fk_publisher_id
    foreign key (publisher_id)
    references publishers (id)
    on delete restrict);

-- Create a "Many to Many" relationship
-- Called "Associative (junction) table" in SQL context
-- A book may have many authors
-- An author may write many book
-- Need to create another table that references both Primary Keys
-- A Primary Key is made of a pair that can not be duplicated

create table if not exists books_authors(
    book_id 	BIGINT not null,
    author_id 	BIGINT not null,
    primary key (book_id, author_id),
    constraint fk_book_id foreign key (book_id) references books (id)
        on delete cascade,
    constraint fk_author_id foreign key (author_id) references authors (id)
        on delete cascade
);