-- CREATE THE MAIN TABLES

create table if not exists publishers(
    id			bigint primary key generated by default as identity,
    name		varchar(50) not null
);

create table if not exists books(
    id			bigint primary key generated by default as identity,
    title		varchar(50) not null
);

create table if not exists authors(
    id			bigint primary key generated by default as identity,
    fullname	varchar(50) not null
);

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

-- SET THE FIRST RELATIONSHIP
-- ADD FK IN BOOKS TO REFERENCE A PUBLISHER ID

-- NOTE: Ideally, it would be a NOT NULL column. For that the process is:
--      1. Create column allowing null
--      2. Fill values with a valid publisher id
--      3. Alter column to be not null
--      4. Add the FK constraint


alter table if exists books
    add column publisher_id bigint;

update books
    set publisher_id = 2;

alter table if exists books
    alter publisher_id set NOT null;

alter table if exists books
    add constraint book_fk_publisher_id
    foreign key (publisher_id)
    references publishers (id)
    on delete restrict;